// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:36e6ebac-8e9d-43da-a778-3165b656d926",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_nNfMZiJWE",
    "aws_user_pools_web_client_id": "6si4kk8tvrmgjl54f8857pgb9s",
    "aws_appsync_graphqlEndpoint": "https://34hmidsepbf3rlu5wfemyng66i.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
